### PR TITLE
Fix interface of Raw nodes to make them extendable again

### LINKED ISSUE #65: mdast-util-to-hast types conflict with hast-util-raw
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-hast@12.2.1 and hast-util-raw@7.2.2

### Link to runnable example

https://github.com/Methuselah96/test-mdast-raw

### Steps to reproduce

1. Add `react-markdown` and `rehype-raw` as dependencies in a project with `skipLibCheck` set to `false`.
2. Add source code that imports the packages.
3. Run type-checking.

### Expected behavior

No type errors.

### Actual behavior

Type errors:

```
node_modules/hast-util-raw/complex-types.d.ts:9:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'raw' must be of type 'Raw', but here has type 'Raw'.

9     raw: Raw
      ~~~

  node_modules/mdast-util-to-hast/complex-types.d.ts:10:5
    10     raw: Raw
           ~~~
    'raw' was also declared here.

node_modules/hast-util-raw/complex-types.d.ts:13:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'raw' must be of type 'Raw', but here has type 'Raw'.

13     raw: Raw
       ~~~

  node_modules/mdast-util-to-hast/complex-types.d.ts:14:5
    14     raw: Raw
           ~~~
    'raw' was also declared here.


Found 2 errors in the same file, starting at: node_modules/hast-util-raw/complex-types.d.ts:9
```

### Affected runtime and version

N/A

### Affected package manager and version

All

### Affected OS and version

N/A

### Build and bundle tools

_No response_

### PR DESCRIPTION
**Pull request by Methuselah96**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Resolves #65.

This PR expands the `eslint-ignore` block introduced in https://github.com/syntax-tree/mdast-util-to-hast/commit/d97bcbdb5c8841e2a6083100a62c5e1bf8d55d6d to include the `Raw` interface to make it compatible with other declarations of the `Raw` type in other packages.

### CODE REVIEW

**Review by JounQin — APPROVED** [review]

File: complex-types.d.ts [hunk 1]
```diff
@@ -1,10 +1,9 @@
 import type {Literal} from 'hast'
 
-export type Raw = {
+export interface Raw extends Literal {
```
Comment (wooorm) [inline complex-types.d.ts:3]: Please check your change locally, as I believe `npm test` will overwrite your changes. To keep them, include the `xo` ignore..

For why, see https://github.com/xojs/xo/releases/tag/v0.52.0.

Comment (Methuselah96) [reply complex-types.d.ts:4]: I see now, thanks. I did run `npm test`, but expected it to cause the script to fail and didn't think to check to see if it overwrote the files.

File: complex-types.d.ts [hunk 2]
```diff
@@ -1,10 +1,10 @@
 import type {Literal} from 'hast'
 
-export type Raw = {
+/* eslint-disable @typescript-eslint/consistent-type-definitions */
```
Comment (ChristianMurphy) [inline complex-types.d.ts:3]: Could `// eslint-disable-next-line @typescript-eslint/consistent-type-definitions` be used to further scope the disable?

Comment (Methuselah96) [reply complex-types.d.ts:3]: Yes, I was just following precedent from https://github.com/syntax-tree/mdast-util-to-hast/commit/d97bcbdb5c8841e2a6083100a62c5e1bf8d55d6d. I'll disable it for each interface individually.

Comment (Methuselah96) [reply complex-types.d.ts]: Done.

**Review by ChristianMurphy — APPROVED** [review]

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Released in [12.2.2](https://github.com/syntax-tree/mdast-util-to-hast/releases/tag/12.2.2)!
